<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search input_image_class mobile-hidden</name>
   <tag></tag>
   <elementGuidId>6a211948-c854-429a-9bec-9907eadd7e1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image_class.mobile-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home_media_banner1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4580d4f-e81e-4011-b107-66bdded207ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>b40f51fb-cc35-4988-bf5b-02e0e88b9d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Black Friday Preview</value>
      <webElementGuid>c2225c34-9a4b-4c65-977e-9dbd542a9646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image_class mobile-hidden</value>
      <webElementGuid>535b3806-cf36-47e2-8b50-2b626a558028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.contentstack.io/v3/assets/blt563c8045b0161467/blt02fd43b9d165f1e4/673392ef568ada31a14e16a1/Sale_Banner.jpg</value>
      <webElementGuid>42961e6d-b6f2-42f5-9ccd-37dcebb8f2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>e67e4382-809b-4a4c-9fb5-993ff9f452ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Banner-template--15136928071813__image_banner_0&quot;)/div[@class=&quot;banner__media media&quot;]/a[@id=&quot;home_media_banner1&quot;]/img[@class=&quot;image_class mobile-hidden&quot;]</value>
      <webElementGuid>88868f9c-07bc-4c0b-8ab1-d8a0b30737ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='home_media_banner1']/img</value>
      <webElementGuid>e2cd29a3-3316-44e7-9c82-69a883a32bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Black Friday Preview']</value>
      <webElementGuid>89f58c0b-8045-430f-b29a-531193181387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>b58a420a-d22e-4bf1-a652-ec8033792457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Black Friday Preview' and @src = 'https://images.contentstack.io/v3/assets/blt563c8045b0161467/blt02fd43b9d165f1e4/673392ef568ada31a14e16a1/Sale_Banner.jpg']</value>
      <webElementGuid>9c353faf-e3f9-4391-8bb6-c7e7989b7bd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
