<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>The iframe for the SM US discount that appears for US ip devices</description>
   <name>attentive_creative_frame</name>
   <tag></tag>
   <elementGuidId>d6ecc35e-4ec6-4415-b357-48f60715b8e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;overlayContainer&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'attentive_creative']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attentive_creative</value>
      <webElementGuid>b0451208-cd09-4352-97a8-693f31de580b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value></value>
      <webElementGuid>3a3bd60b-4b01-4be5-8901-5b41db80cff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
