<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart</name>
   <tag></tag>
   <elementGuidId>9ccea064-372c-41b4-9fda-f291555e1356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addToCartBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addToCartBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4975b8c3-52eb-4ec7-abd5-5f3314bbed5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c4ba2e9-a745-4ef4-9edb-4decc2b47cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-form__cart-submit button btn button-primary</value>
      <webElementGuid>a4e63560-958f-489d-a5eb-7e24d9ba9b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addToCartBtn</value>
      <webElementGuid>596b1431-5bb5-4874-9d41-3bed3312261d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>0caf475c-70fd-410c-9fd9-2c1630b28177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-form&quot;)/button[@id=&quot;addToCartBtn&quot;]</value>
      <webElementGuid>b4e8c374-cc52-42bf-aa67-5e5f419aab48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addToCartBtn']</value>
      <webElementGuid>48255e1b-5126-4664-b77f-a6bf467fb487</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-to-cart-form']/button</value>
      <webElementGuid>19a3d69b-bda7-4fd5-96b6-7923562c6ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size options'])[1]/following::button[1]</value>
      <webElementGuid>6fbfd834-9b7e-47fe-b9ed-2943f3b07ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to give back today?'])[1]/preceding::button[1]</value>
      <webElementGuid>1473253b-410b-46e5-bb59-d6cf28017a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/form/button</value>
      <webElementGuid>b7b01b6e-3090-4fa2-9ea7-63a973f227c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'addToCartBtn' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>667660c4-b99f-4944-a439-607dd80c7478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
