<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to cart</name>
   <tag></tag>
   <elementGuidId>9ccea064-372c-41b4-9fda-f291555e1356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='addToCartBtn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @id = 'addToCartBtn' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addToCartBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc5346c9-d862-438a-a7a4-c7735f333b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a4b1dd25-40b4-4951-a216-f52c44ba16f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-form__cart-submit button btn button-primary</value>
      <webElementGuid>931ead6e-184d-4710-9ddc-8f2a66d5b5ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addToCartBtn</value>
      <webElementGuid>8394449f-451c-4f38-a086-d499d65108d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to cart</value>
      <webElementGuid>52a66720-13de-494e-a1cb-ad5f57c4fb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;add-to-cart-form&quot;)/button[@id=&quot;addToCartBtn&quot;]</value>
      <webElementGuid>b911ecf0-fbff-4cbf-a3d3-feea4f1334b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='addToCartBtn']</value>
      <webElementGuid>9222d19d-8e48-4234-a733-f968207dc216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='add-to-cart-form']/button</value>
      <webElementGuid>eb41339c-3162-49d8-a4d5-e11afc3112a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size options'])[1]/following::button[1]</value>
      <webElementGuid>27225750-2cbb-4959-9e6f-04843956099b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to give back today?'])[1]/preceding::button[1]</value>
      <webElementGuid>569c3907-f76e-4efc-ae9a-6d679b6f72eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/form/button</value>
      <webElementGuid>a93cdee8-1fcd-483d-9827-8af3cd6dc0a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'addToCartBtn' and (text() = 'Add to cart' or . = 'Add to cart')]</value>
      <webElementGuid>1495a228-86fb-490e-a23f-ba457fdebba8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
