<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Filters_product-img svelte-1keq2mf</name>
   <tag></tag>
   <elementGuidId>442db4fd-46f5-4270-aa8f-1a71ef3a871c</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>product-container fs-results-product-card svelte-133i5ix product-card-border</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fs-ssr-app-content&quot;]/div[2]/div[4]/div/div[1]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://cdn.shopify.com/s/files/1/2170/8465/files/STEVEMADDEN_SHOES_SELENA_CHESTNUT.jpg?width=417&amp;v=1701445662' and @alt = 'SELENA COGNAC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f776775c-9cee-4c33-8939-b9531cc9c4a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.shopify.com/s/files/1/2170/8465/files/STEVEMADDEN_SHOES_SELENA_CHESTNUT.jpg?width=417&amp;v=1701445662</value>
      <webElementGuid>32c51603-0ab6-461e-8a17-10d94d97cd2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a6ba4ff5-f200-4c24-bb3c-f97633000572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SELENA COGNAC</value>
      <webElementGuid>d2eb97d3-42fd-40c3-aa60-51d9a7acef6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-img svelte-1keq2mf</value>
      <webElementGuid>9a1cccab-4df2-4a40-8943-28fc3d9b2135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>6c83852c-2575-4f75-a909-a7b658b4b127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>fe6424c3-5c81-434c-b4a6-db285bf07ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>f9f1f62b-6cee-48b5-86c4-6aacf41752df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fs-ssr-app-content&quot;)/div[@class=&quot;fs-app-content filters-grid-wrapper svelte-kesx38&quot;]/div[@class=&quot;fs-app-content-center-block&quot;]/div[@class=&quot;grid-container svelte-tumrrf&quot;]/div[@class=&quot;product-container fs-results-product-card svelte-133i5ix product-card-border&quot;]/a[@class=&quot;fs-product-image-link svelte-133i5ix&quot;]/div[@class=&quot;img-container image-wrapper svelte-133i5ix&quot;]/div[@class=&quot;fs-product-main-image-wrapper&quot;]/img[@class=&quot;product-img svelte-1keq2mf&quot;]</value>
      <webElementGuid>71e7f480-b256-49b1-bbb9-87845c094042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;fs-ssr-app-content&quot;]/div[2]/div[4]/div/div[1]/a/div/div[3]</value>
      <webElementGuid>4890d46e-3df7-40c6-b687-1a8d5dc56453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SELENA COGNAC']</value>
      <webElementGuid>b041891c-4118-4e96-b690-10a81a66b580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/img</value>
      <webElementGuid>efd3f61f-3b43-40ba-8795-4af9dc9cb247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.shopify.com/s/files/1/2170/8465/files/STEVEMADDEN_SHOES_SELENA_CHESTNUT.jpg?width=417&amp;v=1701445662' and @alt = 'SELENA COGNAC']</value>
      <webElementGuid>9978836d-7791-45fd-9861-eeadf3f0899a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
