<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Search input_image_class mobile-hidden</name>
   <tag></tag>
   <elementGuidId>b2adf9ca-3465-4826-afe9-0bd9a33ab06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.image_class.mobile-hidden</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='home_media_banner1']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f26f59bb-d364-4dfb-9459-632a578fee3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>b71620c1-be8c-40f1-b541-5dec1038b141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Black Friday Preview</value>
      <webElementGuid>cf87438e-c44b-46a1-aaab-7fc4aa47ddfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image_class mobile-hidden</value>
      <webElementGuid>e36d3d6a-ba85-4003-bb13-69077da94958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://images.contentstack.io/v3/assets/blt563c8045b0161467/blt02fd43b9d165f1e4/673392ef568ada31a14e16a1/Sale_Banner.jpg</value>
      <webElementGuid>45aeddff-53f2-4099-9ce8-9e29dce4fd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>14ee2a78-1403-4b5c-b6ce-15e583867f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Banner-template--15136928071813__image_banner_0&quot;)/div[@class=&quot;banner__media media&quot;]/a[@id=&quot;home_media_banner1&quot;]/img[@class=&quot;image_class mobile-hidden&quot;]</value>
      <webElementGuid>6170bf0e-d8a1-43ea-ba57-97351ab55a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='home_media_banner1']/img</value>
      <webElementGuid>0f423712-d0ac-4535-886f-3ef21b2d42e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Black Friday Preview']</value>
      <webElementGuid>79b12d6b-48ca-492f-b64d-324d8eef72e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>73f95983-b339-4e18-9831-3d1e04152539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Black Friday Preview' and @src = 'https://images.contentstack.io/v3/assets/blt563c8045b0161467/blt02fd43b9d165f1e4/673392ef568ada31a14e16a1/Sale_Banner.jpg']</value>
      <webElementGuid>fdff735a-c9cf-46e2-896d-bec98fbcbbae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
