<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_EXCLUSIVE_product-img svelte-1keq2mf</name>
   <tag></tag>
   <elementGuidId>b32897b8-0e30-46d5-a8fa-d660e0968eda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.product-img.svelte-1keq2mf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fs-ssr-app-content']/div[2]/div[4]/div/div/a/div/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a43e1a9-9486-4e36-bacd-94198d7afb21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.shopify.com/s/files/1/2170/8465/files/STEVEMADDEN_SHOES_SELENA_CHESTNUT.jpg?width=417&amp;v=1701445662</value>
      <webElementGuid>666042fa-af6d-49f5-92e6-c3982b3451a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>b9dd19b6-4e77-4947-bc0f-79b327f0fc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>SELENA COGNAC</value>
      <webElementGuid>a6a3102b-507d-46bc-94c1-faab858ba518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-img svelte-1keq2mf</value>
      <webElementGuid>8d9dd5e2-5191-4528-aafe-7eae57369392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>d855aa66-a5d6-4bee-8691-96bb02dbcf9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>acc9b322-ce92-44fd-81f8-d2e2d914d629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>110886f2-a46c-4821-8746-23ec611082d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fs-ssr-app-content&quot;)/div[@class=&quot;fs-app-content filters-grid-wrapper svelte-kesx38 fs-hide-filters&quot;]/div[@class=&quot;fs-app-content-center-block&quot;]/div[@class=&quot;grid-container svelte-tumrrf&quot;]/div[@class=&quot;product-container fs-results-product-card svelte-133i5ix product-card-border&quot;]/a[@class=&quot;fs-product-image-link svelte-133i5ix&quot;]/div[@class=&quot;img-container image-wrapper svelte-133i5ix&quot;]/div[@class=&quot;fs-product-main-image-wrapper&quot;]/img[@class=&quot;product-img svelte-1keq2mf&quot;]</value>
      <webElementGuid>3565428b-c268-4c8e-bd4c-d5ea35f36c6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fs-ssr-app-content']/div[2]/div[4]/div/div/a/div/div[3]/img</value>
      <webElementGuid>edbda04d-1cac-4735-af7f-7be2667b388a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='SELENA COGNAC']</value>
      <webElementGuid>468d69e0-d2fb-45f8-bc27-24ed3b862531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>a72e510a-8b7a-4ac4-bfba-1b360e88dc3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn.shopify.com/s/files/1/2170/8465/files/STEVEMADDEN_SHOES_SELENA_CHESTNUT.jpg?width=417&amp;v=1701445662' and @alt = 'SELENA COGNAC']</value>
      <webElementGuid>b3dc1149-8df1-4bb0-bada-7cdc1691d2ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
